window.SHOPEE_CATEGORIES = [
  { en: "Health > Food Supplement", ko: "건강 > 건강기능식품" },
  { en: "Health > Others", ko: "건강 > 기타" },
  { en: "Health > Medical Supplies", ko: "건강 > 의료용품" },
  { en: "Health > Personal Care", ko: "건강 > 개인 위생용품" },
  { en: "Health > Sexual Wellness", ko: "건강 > 성인용품" },
  { en: "Fashion Accessories > Rings", ko: "패션 액세서리 > 반지" },
  { en: "Fashion Accessories > Earrings", ko: "패션 액세서리 > 귀걸이" },
  { en: "Fashion Accessories > Scarves & Shawls", ko: "패션 액세서리 > 스카프 & 숄" },
  { en: "Fashion Accessories > Gloves", ko: "패션 액세서리 > 장갑" },
  { en: "Fashion Accessories > Hair Accessories", ko: "패션 액세서리 > 헤어 액세서리" },
  { en: "Fashion Accessories > Bracelets & Bangles", ko: "패션 액세서리 > 팔찌 & 뱅글" },
  { en: "Fashion Accessories > Anklets", ko: "패션 액세서리 > 발찌" },
  { en: "Fashion Accessories > Hats & Caps", ko: "패션 액세서리 > 모자" },
  { en: "Fashion Accessories > Necklaces", ko: "패션 액세서리 > 목걸이" },
  { en: "Fashion Accessories > Eyewear", ko: "패션 액세서리 > 안경 및 선글라스" },
  { en: "Fashion Accessories > Investment Precious Metals", ko: "패션 액세서리 > 투자용 귀금속" },
  { en: "Fashion Accessories > Belts", ko: "패션 액세서리 > 벨트" },
  { en: "Fashion Accessories > Neckties, Bow Ties & Cravats", ko: "패션 액세서리 > 넥타이 & 나비넥타이" },
  { en: "Fashion Accessories > Additional Accessories", ko: "패션 액세서리 > 기타 액세서리" },
  { en: "Fashion Accessories > Accessories Sets & Packages", ko: "패션 액세서리 > 액세서리 세트" },
  { en: "Fashion Accessories > Others", ko: "패션 액세서리 > 기타" },
  { en: "Fashion Accessories > Fine Jewelry", ko: "패션 액세서리 > 파인 쥬얼리" },
  { en: "Home Appliances > Projectors & Accessories", ko: "가전제품 > 프로젝터 및 액세서리" },
  { en: "Home Appliances > Small Household Appliances", ko: "가전제품 > 소형 가전" },
  { en: "Home Appliances > Large Household Appliances", ko: "가전제품 > 대형 가전" },
  { en: "Home Appliances > TVs & Accessories", ko: "가전제품 > TV 및 액세서리" },
  { en: "Home Appliances > Kitchen Appliances", ko: "가전제품 > 주방 가전" },
  { en: "Home Appliances > Electrical Circuitry & Parts", ko: "가전제품 > 전기 회로 및 부품" },
  { en: "Home Appliances > Batteries", ko: "가전제품 > 배터리" },
  { en: "Home Appliances > E-Cigarettes", ko: "가전제품 > 전자담배" },
  { en: "Home Appliances > Remote Controls", ko: "가전제품 > 리모컨" },
  { en: "Home Appliances > Others", ko: "가전제품 > 기타" },
  { en: "Men Clothes > Jeans", ko: "남성의류 > 청바지" },
  { en: "Men Clothes > Hoodies & Sweatshirts", ko: "남성의류 > 후드 및 스웨트셔츠" },
  { en: "Men Clothes > Sweaters & Cardigans", ko: "남성의류 > 스웨터 및 가디건" },
  { en: "Men Clothes > Jackets, Coats & Vests", ko: "남성의류 > 재킷, 코트 및 조끼" },
  { en: "Men Clothes > Suits", ko: "남성의류 > 정장" },
  { en: "Men Clothes > Pants", ko: "남성의류 > 바지" },
  { en: "Men Clothes > Shorts", ko: "남성의류 > 반바지" },
  { en: "Men Clothes > Tops", ko: "남성의류 > 상의" },
  { en: "Men Clothes > Innerwear & Underwear", ko: "남성의류 > 이너웨어 및 속옷" },
  { en: "Men Clothes > Sleepwear", ko: "남성의류 > 잠옷" },
  { en: "Men Clothes > Sets", ko: "남성의류 > 세트 의류" },
  { en: "Men Clothes > Traditional Wear", ko: "남성의류 > 전통 의상" },
  { en: "Men Clothes > Costumes", ko: "남성의류 > 코스튬" },
  { en: "Men Clothes > Occupational Attire", ko: "남성의류 > 작업복" },
  { en: "Men Clothes > Others", ko: "남성의류 > 기타" },
  { en: "Men Clothes > Socks", ko: "남성의류 > 양말" },
  { en: "Men Shoes > Boots", ko: "남성신발 > 부츠" },
  { en: "Men Shoes > Sneakers", ko: "남성신발 > 스니커즈" },
  { en: "Men Shoes > Slip Ons & Mules", ko: "남성신발 > 슬립온 및 뮬" },
  { en: "Men Shoes > Loafers & Boat Shoes", ko: "남성신발 > 로퍼 및 보트 슈즈" },
  { en: "Men Shoes > Oxfords & Lace-Ups", ko: "남성신발 > 옥스포드 및 레이스업" },
  { en: "Men Shoes > Sandals & Flip Flops", ko: "남성신발 > 샌들 및 플립플롭" },
  { en: "Men Shoes > Shoe Care & Accessories", ko: "남성신발 > 신발 관리 및 액세서리" },
  { en: "Men Shoes > Others", ko: "남성신발 > 기타" },
  { en: "Mobile & Gadgets > Sim Cards", ko: "모바일 & 기기 > 유심 카드" },
  { en: "Mobile & Gadgets > Tablets", ko: "모바일 & 기기 > 태블릿" },
  { en: "Mobile & Gadgets > Mobile Phones", ko: "모바일 & 기기 > 휴대폰" },
  { en: "Mobile & Gadgets > Wearable Devices", ko: "모바일 & 기기 > 웨어러블 기기" },
  { en: "Mobile & Gadgets > Accessories", ko: "모바일 & 기기 > 모바일 액세서리" },
  { en: "Mobile & Gadgets > Walkie Talkies", ko: "모바일 & 기기 > 무전기" },
  { en: "Mobile & Gadgets > Others", ko: "모바일 & 기기 > 기타" },
  { en: "Muslim Fashion > Women Muslim Wear", ko: "무슬림 패션 > 여성 무슬림 의류" },
  { en: "Muslim Fashion > Prayer Attire & Equipment", ko: "무슬림 패션 > 기도 복장 및 장비" },
  { en: "Muslim Fashion > Men Muslim Wear", ko: "무슬림 패션 > 남성 무슬림 의류" },
  { en: "Muslim Fashion > Kid Muslim Wear", ko: "무슬림 패션 > 아동 무슬림 의류" },
  { en: "Muslim Fashion > Outerwear", ko: "무슬림 패션 > 아우터" },
  { en: "Muslim Fashion > Sets", ko: "무슬림 패션 > 세트" },
  { en: "Muslim Fashion > Others", ko: "무슬림 패션 > 기타" },
  { en: "Travel & Luggage > Luggage", ko: "여행용품 > 캐리어" },
  { en: "Travel & Luggage > Travel Bags", ko: "여행용품 > 여행 가방" },
  { en: "Travel & Luggage > Travel Accessories", ko: "여행용품 > 여행 액세서리" },
  { en: "Travel & Luggage > Others", ko: "여행용품 > 기타" },
  { en: "Women Bags > Backpacks", ko: "여성가방 > 백팩" },
  { en: "Women Bags > Laptop Bags", ko: "여성가방 > 노트북 가방" },
  { en: "Women Bags > Clutches & Wristlets", ko: "여성가방 > 클러치 및 파우치" },
  { en: "Women Bags > Waist Bags & Chest Bags", ko: "여성가방 > 웨이스트 및 체스트 백" },
  { en: "Women Bags > Tote Bags", ko: "여성가방 > 토트백" },
  { en: "Women Bags > Top-handle Bags", ko: "여성가방 > 탑핸들 백" },
  { en: "Women Bags > Crossbody & Shoulder Bags", ko: "여성가방 > 크로스 및 숄더 백" },
  { en: "Women Bags > Wallets", ko: "여성가방 > 지갑" },
  { en: "Women Bags > Bag Accessories", ko: "여성가방 > 가방 액세서리" },
  { en: "Women Bags > Others", ko: "여성가방 > 기타" },
  { en: "Women Clothes > Tops", ko: "여성의류 > 상의" },
  { en: "Women Clothes > Pants & Leggings", ko: "여성의류 > 바지 및 레깅스" },
  { en: "Women Clothes > Shorts", ko: "여성의류 > 반바지" },
  { en: "Women Clothes > Skirts", ko: "여성의류 > 스커트" },
  { en: "Women Clothes > Jeans", ko: "여성의류 > 청바지" },
  { en: "Women Clothes > Dresses", ko: "여성의류 > 드레스/원피스" },
  { en: "Women Clothes > Wedding Dresses", ko: "여성의류 > 웨딩 드레스" },
  { en: "Women Clothes > Jumpsuits, Playsuits & Overalls", ko: "여성의류 > 점프수트 및 오버올" },
  { en: "Women Clothes > Jackets, Coats & Vests", ko: "여성의류 > 재킷, 코트 및 조끼" },
  { en: "Women Clothes > Sweaters & Cardigans", ko: "여성의류 > 스웨터 및 가디건" },
  { en: "Women Clothes > Hoodies & Sweatshirts", ko: "여성의류 > 후드 및 스웨트셔츠" },
  { en: "Women Clothes > Sets", ko: "여성의류 > 세트 의류" },
  { en: "Women Clothes > Lingerie & Underwear", ko: "여성의류 > 란제리 및 속옷" },
  { en: "Women Clothes > Sleepwear & Pajamas", ko: "여성의류 > 잠옷 및 파자마" },
  { en: "Women Clothes > Maternity Wear", ko: "여성의류 > 임부복" },
  { en: "Women Clothes > Traditional Wear", ko: "여성의류 > 전통 의상" },
  { en: "Women Clothes > Costumes", ko: "여성의류 > 코스튬" },
  { en: "Women Clothes > Others", ko: "여성의류 > 기타" },
  { en: "Women Clothes > Fabric", ko: "여성의류 > 원단" },
  { en: "Women Clothes > Socks & Stockings", ko: "여성의류 > 양말 및 스타킹" },
  { en: "Women Shoes > Boots", ko: "여성신발 > 부츠" },
  { en: "Women Shoes > Sneakers", ko: "여성신발 > 스니커즈" },
  { en: "Women Shoes > Flats", ko: "여성신발 > 플랫 슈즈" },
  { en: "Women Shoes > Heels", ko: "여성신발 > 힐" },
  { en: "Women Shoes > Wedges", ko: "여성신발 > 웨지힐" },
  { en: "Women Shoes > Flat Sandals & Flip Flops", ko: "여성신발 > 플랫 샌들 및 플립플롭" },
  { en: "Women Shoes > Shoe Care & Accessories", ko: "여성신발 > 신발 관리 및 액세서리" },
  { en: "Women Shoes > Others", ko: "여성신발 > 기타" },
  { en: "Men Bags > Backpacks", ko: "남성가방 > 백팩" },
  { en: "Men Bags > Laptop Bags", ko: "남성가방 > 노트북 가방" },
  { en: "Men Bags > Tote Bags", ko: "남성가방 > 토트백" },
  { en: "Men Bags > Briefcases", ko: "남성가방 > 서류 가방" },
  { en: "Men Bags > Clutches", ko: "남성가방 > 클러치" },
  { en: "Men Bags > Waist Bags & Chest Bags", ko: "남성가방 > 웨이스트 및 체스트 백" },
  { en: "Men Bags > Crossbody & Shoulder Bags", ko: "남성가방 > 크로스 및 숄더 백" },
  { en: "Men Bags > Wallets", ko: "남성가방 > 지갑" },
  { en: "Men Bags > Others", ko: "남성가방 > 기타" },
  { en: "Watches > Women Watches", ko: "시계 > 여성용 시계" },
  { en: "Watches > Men Watches", ko: "시계 > 남성용 시계" },
  { en: "Watches > Set & Couple Watches", ko: "시계 > 커플 시계 세트" },
  { en: "Watches > Watches Accessories", ko: "시계 > 시계 액세서리" },
  { en: "Watches > Others", ko: "시계 > 기타" },
  { en: "Audio > Earphones, Headphones & Headsets", ko: "오디오 > 이어폰, 헤드폰 & 헤드셋" },
  { en: "Audio > Media Players", ko: "오디오 > 미디어 플레이어" },
  { en: "Audio > Microphones", ko: "오디오 > 마이크" },
  { en: "Audio > Amplifiers & Mixers", ko: "오디오 > 앰프 및 믹서" },
  { en: "Audio > Home Audio & Speakers", ko: "오디오 > 홈 오디오 및 스피커" },
  { en: "Audio > Audio & Video Cables & Converters", ko: "오디오 > 오디오/비디오 케이블 및 컨버터" },
  { en: "Audio > Others", ko: "오디오 > 기타" },
  { en: "Food & Beverages > Convenience / Ready-to-eat", ko: "식품 > 간편식 / 즉석식품" },
  { en: "Food & Beverages > Snacks", ko: "식품 > 스낵" },
  { en: "Food & Beverages > Food Staples", ko: "식품 > 주식재료" },
  { en: "Food & Beverages > Cooking Essentials", ko: "식품 > 요리 재료" },
  { en: "Food & Beverages > Baking Needs", ko: "식품 > 베이킹 재료" },
  { en: "Food & Beverages > Breakfast Cereals & Spread", ko: "식품 > 시리얼 및 스프레드" },
  { en: "Food & Beverages > Beverages", ko: "식품 > 음료" },
  { en: "Food & Beverages > Dairy & Eggs", ko: "식품 > 유제품 및 계란" },
  { en: "Food & Beverages > Fresh & Frozen Food", ko: "식품 > 신선 및 냉동 식품" },
  { en: "Food & Beverages > Bakery", ko: "식품 > 베이커리" },
  { en: "Food & Beverages > Alcoholic Beverages", ko: "식품 > 주류" },
  { en: "Food & Beverages > Gift Set & Hampers", ko: "식품 > 선물 세트" },
  { en: "Food & Beverages > Others", ko: "식품 > 기타" },
  { en: "Beauty > Hand, Foot & Nail Care", ko: "뷰티 > 손, 발 및 네일 케어" },
  { en: "Beauty > Hair Care", ko: "뷰티 > 헤어 케어" },
  { en: "Beauty > Men's Care", ko: "뷰티 > 남성 케어" },
  { en: "Beauty > Perfumes & Fragrances", ko: "뷰티 > 향수" },
  { en: "Beauty > Makeup", ko: "뷰티 > 메이크업" },
  { en: "Beauty > Beauty Tools", ko: "뷰티 > 뷰티 소품" },
  { en: "Beauty > Skincare", ko: "뷰티 > 스킨케어" },
  { en: "Beauty > Beauty Sets & Packages", ko: "뷰티 > 뷰티 세트" },
  { en: "Beauty > Others", ko: "뷰티 > 기타" },
  { en: "Beauty > Bath & Body Care", ko: "뷰티 > 바디 및 목욕 용품" },
  { en: "Pets > Pet Food", ko: "반려동물 > 펫푸드" },
  { en: "Pets > Pet Accessories", ko: "반려동물 > 펫 액세서리" },
  { en: "Pets > Litter & Toilet", ko: "반려동물 > 배변 용품" },
  { en: "Pets > Pet Grooming", ko: "반려동물 > 미용 용품" },
  { en: "Pets > Pet Clothing & Accessories", ko: "반려동물 > 반려동물 의류 및 액세서리" },
  { en: "Pets > Pet Healthcare", ko: "반려동물 > 건강 관리 용품" },
  { en: "Pets > Others", ko: "반려동물 > 기타" },
  { en: "Mom & Baby > Baby Travel Essentials", ko: "유아동 > 외출 용품" },
  { en: "Mom & Baby > Feeding Essentials", ko: "유아동 > 수유 용품" },
  { en: "Mom & Baby > Maternity Accessories", ko: "유아동 > 임산부 액세서리" },
  { en: "Mom & Baby > Maternity Healthcare", ko: "유아동 > 임산부 건강 용품" },
  { en: "Mom & Baby > Bath & Body Care", ko: "유아동 > 목욕 및 스킨케어" },
  { en: "Mom & Baby > Nursery", ko: "유아동 > 유아방 용품" },
  { en: "Mom & Baby > Baby Safety", ko: "유아동 > 안전 용품" },
  { en: "Mom & Baby > Milk Formula & Baby Food", ko: "유아동 > 분유 및 이유식" },
  { en: "Mom & Baby > Baby Healthcare", ko: "유아동 > 유아 건강 용품" },
  { en: "Mom & Baby > Diapering & Potty", ko: "유아동 > 기저귀 및 배변 훈련" },
  { en: "Mom & Baby > Toys", ko: "유아동 > 장난감" },
  { en: "Mom & Baby > Gift Sets & Packages", ko: "유아동 > 선물 세트" },
  { en: "Mom & Baby > Others", ko: "유아동 > 기타" },
  { en: "Baby & Kids Fashion > Baby Clothes", ko: "유아동 의류 > 유아복" },
  { en: "Baby & Kids Fashion > Baby Mittens & Footwear", ko: "유아동 의류 > 유아 장갑 및 신발" },
  { en: "Baby & Kids Fashion > Baby & Kids Accessories", ko: "유아동 의류 > 유아동 액세서리" },
  { en: "Baby & Kids Fashion > Boy Clothes", ko: "유아동 의류 > 남아복" },
  { en: "Baby & Kids Fashion > Girl Clothes", ko: "유아동 의류 > 여아복" },
  { en: "Baby & Kids Fashion > Boy Shoes", ko: "유아동 의류 > 남아 신발" },
  { en: "Baby & Kids Fashion > Girl Shoes", ko: "유아동 의류 > 여아 신발" },
  { en: "Baby & Kids Fashion > Others", ko: "유아동 의류 > 기타" },
  { en: "Gaming & Consoles > Console Machines", ko: "게임 및 콘솔 > 콘솔 기기" },
  { en: "Gaming & Consoles > Console Accessories", ko: "게임 및 콘솔 > 콘솔 액세서리" },
  { en: "Gaming & Consoles > Video Games", ko: "게임 및 콘솔 > 비디오 게임" },
  { en: "Gaming & Consoles > Others", ko: "게임 및 콘솔 > 기타" },
  { en: "Cameras & Drones > Cameras", ko: "카메라 & 드론 > 카메라" },
  { en: "Cameras & Drones > Security Cameras & Systems", ko: "카메라 & 드론 > 보안 카메라 및 시스템" },
  { en: "Cameras & Drones > Lenses", ko: "카메라 & 드론 > 렌즈" },
  { en: "Cameras & Drones > Lens Accessories", ko: "카메라 & 드론 > 렌즈 액세서리" },
  { en: "Cameras & Drones > Camera Accessories", ko: "카메라 & 드론 > 카메라 액세서리" },
  { en: "Cameras & Drones > Camera Care", ko: "카메라 & 드론 > 카메라 관리 용품" },
  { en: "Cameras & Drones > Drones", ko: "카메라 & 드론 > 드론" },
  { en: "Cameras & Drones > Drone Accessories", ko: "카메라 & 드론 > 드론 액세서리" },
  { en: "Cameras & Drones > Others", ko: "카메라 & 드론 > 기타" },
  { en: "Home & Living > Home Fragrance & Aromatherapy", ko: "홈 & 리빙 > 방향제 및 아로마테라피" },
  { en: "Home & Living > Bathrooms", ko: "홈 & 리빙 > 욕실 용품" },
  { en: "Home & Living > Bedding", ko: "홈 & 리빙 > 침구류" },
  { en: "Home & Living > Decoration", ko: "홈 & 리빙 > 인테리어 소품" },
  { en: "Home & Living > Hand Warmers, Hot Water Bags & Ice Bags", ko: "홈 & 리빙 > 핫팩 및 얼음 주머니" },
  { en: "Home & Living > Furniture", ko: "홈 & 리빙 > 가구" },
  { en: "Home & Living > Gardening", ko: "홈 & 리빙 > 원예 용품" },
  { en: "Home & Living > Tools & Home Improvement", ko: "홈 & 리빙 > 공구 및 집수리 용품" },
  { en: "Home & Living > Home Care Supplies", ko: "홈 & 리빙 > 홈케어 용품" },
  { en: "Home & Living > Kitchenware", ko: "홈 & 리빙 > 주방 용품" },
  { en: "Home & Living > Dinnerware", ko: "홈 & 리빙 > 식기류" },
  { en: "Home & Living > Lighting", ko: "홈 & 리빙 > 조명" },
  { en: "Home & Living > Safety & Security", ko: "홈 & 리빙 > 안전 및 보안 용품" },
  { en: "Home & Living > Home Organizers", ko: "홈 & 리빙 > 수납 및 정리 용품" },
  { en: "Home & Living > Party Supplies", ko: "홈 & 리빙 > 파티 용품" },
  { en: "Home & Living > Fengshui & Religious Supplies", ko: "홈 & 리빙 > 풍수 및 종교 용품" },
  { en: "Home & Living > Others", ko: "홈 & 리빙 > 기타" },
  { en: "Sports & Outdoors > Sports & Outdoor Recreation Equipments", ko: "스포츠 & 아웃도어 > 스포츠 및 야외 레크리에이션 장비" },
  { en: "Sports & Outdoors > Sports Footwear", ko: "스포츠 & 아웃도어 > 스포츠화" },
  { en: "Sports & Outdoors > Sports & Outdoor Apparels", ko: "스포츠 & 아웃도어 > 스포츠 및 아웃도어 의류" },
  { en: "Sports & Outdoors > Sports & Outdoor Accessories", ko: "스포츠 & 아웃도어 > 스포츠 및 아웃도어 액세서리" },
  { en: "Sports & Outdoors > Others", ko: "스포츠 & 아웃도어 > 기타" },
  { en: "Stationery > Gift & Wrapping", ko: "문구류 > 선물 포장" },
  { en: "Stationery > Writing & Correction", ko: "문구류 > 필기구 및 수정 용품" },
  { en: "Stationery > School & Office Equipment", ko: "문구류 > 학용품 및 사무 기기" },
  { en: "Stationery > Art Supplies", ko: "문구류 > 미술 용품" },
  { en: "Stationery > Notebooks & Papers", ko: "문구류 > 노트 및 종이류" },
  { en: "Stationery > Letters & Envelopes", ko: "문구류 > 편지 및 봉투" },
  { en: "Stationery > Others", ko: "문구류 > 기타" },
  { en: "Hobbies & Collections > Collectible Items", ko: "취미 및 수집 > 수집품" },
  { en: "Hobbies & Collections > Souvenirs", ko: "취미 및 수집 > 기념품" },
  { en: "Hobbies & Collections > Toys & Games", ko: "취미 및 수집 > 장난감 및 게임" },
  { en: "Hobbies & Collections > CD, DVD & Bluray", ko: "취미 및 수집 > CD, DVD & 블루레이" },
  { en: "Hobbies & Collections > Musical Instruments & Accessories", ko: "취미 및 수집 > 악기 및 액세서리" },
  { en: "Hobbies & Collections > Vinyl Records", ko: "취미 및 수집 > 바이닐 음반" },
  { en: "Hobbies & Collections > Photo Albums", ko: "취미 및 수집 > 사진 앨범" },
  { en: "Hobbies & Collections > Needlework", ko: "취미 및 수집 > 수예 용품" },
  { en: "Hobbies & Collections > Others", ko: "취미 및 수집 > 기타" },
  { en: "Automobiles > Automobiles", ko: "자동차 > 자동차 차량" },
  { en: "Automobiles > Automobile Interior Accessories", ko: "자동차 > 자동차 인테리어 액세서리" },
  { en: "Automobiles > Automobile Exterior Accessories", ko: "자동차 > 자동차 익스테리어 액세서리" },
  { en: "Automobiles > Automobile Spare Parts", ko: "자동차 > 자동차 예비 부품" },
  { en: "Automobiles > Automotive Tools", ko: "자동차 > 자동차 공구" },
  { en: "Automobiles > Automotive Care", ko: "자동차 > 자동차 관리 용품" },
  { en: "Automobiles > Automotive Oils & Lubes", ko: "자동차 > 자동차 오일 및 윤활유" },
  { en: "Automobiles > Automotive Keychains & Key Covers", ko: "자동차 > 자동차 키링 및 키 커버" },
  { en: "Automobiles > Others", ko: "자동차 > 기타" },
  { en: "Automobiles > Automotive Services & Installations", ko: "자동차 > 자동차 서비스 및 설치" },
  { en: "Motorcycles > Motorcycles", ko: "오토바이 > 오토바이" },
  { en: "Motorcycles > Motorcycle Accessories", ko: "오토바이 > 오토바이 액세서리" },
  { en: "Motorcycles > Motorcycle Spare Parts", ko: "오토바이 > 오토바이 예비 부품" },
  { en: "Motorcycles > Motorcycle Helmets & Accessories", ko: "오토바이 > 오토바이 헬멧 및 액세서리" },
  { en: "Motorcycles > Others", ko: "오토바이 > 기타" },
  { en: "Tickets, Vouchers & Services > Events & Attractions", ko: "티켓 및 서비스 > 이벤트 및 명소" },
  { en: "Tickets, Vouchers & Services > F&B", ko: "티켓 및 서비스 > 식음료 바우처" },
  { en: "Tickets, Vouchers & Services > Shopping", ko: "티켓 및 서비스 > 쇼핑 바우처" },
  { en: "Tickets, Vouchers & Services > Utilities", ko: "티켓 및 서비스 > 공과금" },
  { en: "Tickets, Vouchers & Services > Services", ko: "티켓 및 서비스 > 서비스" },
  { en: "Tickets, Vouchers & Services > Beauty & Wellness", ko: "티켓 및 서비스 > 뷰티 및 스파" },
  { en: "Tickets, Vouchers & Services > Transport", ko: "티켓 및 서비스 > 교통 서비스" },
  { en: "Tickets, Vouchers & Services > Lessons & Workshops", ko: "티켓 및 서비스 > 레슨 및 워크샵" },
  { en: "Tickets, Vouchers & Services > Telco", ko: "티켓 및 서비스 > 통신" },
  { en: "Tickets, Vouchers & Services > Travel", ko: "티켓 및 서비스 > 여행" },
  { en: "Tickets, Vouchers & Services > E-Money", ko: "티켓 및 서비스 > 전자화폐" },
  { en: "Tickets, Vouchers & Services > Real Estate", ko: "티켓 및 서비스 > 부동산" },
  { en: "Tickets, Vouchers & Services > Gaming & App Stores", ko: "티켓 및 서비스 > 게임 및 앱 스토어" },
  { en: "Tickets, Vouchers & Services > Streaming", ko: "티켓 및 서비스 > 스트리밍 서비스" },
  { en: "Tickets, Vouchers & Services > Shopee", ko: "티켓 및 서비스 > 쇼피" },
  { en: "Tickets, Vouchers & Services > Others", ko: "티켓 및 서비스 > 기타" },
  { en: "Books & Magazines > Magazines & Newspaper", ko: "도서 및 잡지 > 잡지 및 신문" },
  { en: "Books & Magazines > Books", ko: "도서 및 잡지 > 도서" },
  { en: "Books & Magazines > E-Books", ko: "도서 및 잡지 > e-북" },
  { en: "Books & Magazines > Others", ko: "도서 및 잡지 > 기타" },
  { en: "Computers & Accessories > Desktop Computers", ko: "컴퓨터 및 주변기기 > 데스크탑" },
  { en: "Computers & Accessories > Monitors", ko: "컴퓨터 및 주변기기 > 모니터" },
  { en: "Computers & Accessories > Desktop & Laptop Components", ko: "컴퓨터 및 주변기기 > 데스크탑 및 노트북 부품" },
  { en: "Computers & Accessories > Data Storage", ko: "컴퓨터 및 주변기기 > 데이터 스토리지" },
  { en: "Computers & Accessories > Network Components", ko: "컴퓨터 및 주변기기 > 네트워크 장비" },
  { en: "Computers & Accessories > Softwares", ko: "컴퓨터 및 주변기기 > 소프트웨어" },
  { en: "Computers & Accessories > Office Equipment", ko: "컴퓨터 및 주변기기 > 사무용 기기" },
  { en: "Computers & Accessories > Printers & Scanners", ko: "컴퓨터 및 주변기기 > 프린터 및 스캐너" },
  { en: "Computers & Accessories > Peripherals & Accessories", ko: "컴퓨터 및 주변기기 > 주변기기 및 액세서리" },
  { en: "Computers & Accessories > Keyboards & Mice", ko: "컴퓨터 및 주변기기 > 키보드 및 마우스" },
  { en: "Computers & Accessories > Laptops", ko: "컴퓨터 및 주변기기 > 노트북" },
  { en: "Computers & Accessories > Others", ko: "컴퓨터 및 주변기기 > 기타" },
  { en: "Deals Near Me > ShopeePay Voucher", ko: "내 근처 딜 > 쇼피페이 바우처" },
  { en: "Deals Near Me > Deal Voucher", ko: "내 근처 딜 > 딜 바우처" },
  { en: "Spare Parts and Accessories for Vehicles > Heavy Duty and Boats", ko: "차량 예비 부품 및 액세서리 > 대형 차량 및 보트" },
  { en: "Spare Parts and Accessories for Vehicles > Spare Parts for Automobiles", ko: "차량 예비 부품 및 액세서리 > 자동차 예비 부품" },
  { en: "Spare Parts and Accessories for Vehicles > External Accessories for Automobiles", ko: "차량 예비 부품 및 액세서리 > 자동차 익스테리어 액세서리" },
  { en: "Spare Parts and Accessories for Vehicles > Internal Accessories for Automobiles", ko: "차량 예비 부품 및 액세서리 > 자동차 인테리어 액세서리" },
  { en: "Spare Parts and Accessories for Vehicles > Spare Parts for Motorcycles", ko: "차량 예비 부품 및 액세서리 > 오토바이 예비 부품" },
  { en: "Spare Parts and Accessories for Vehicles > Accessories for Motorcycles", ko: "차량 예비 부품 및 액세서리 > 오토바이 액세서리" },
  { en: "Spare Parts and Accessories for Vehicles > Tires and Wheels", ko: "차량 예비 부품 및 액세서리 > 타이어 및 휠" },
  { en: "Spare Parts and Accessories for Vehicles > Vehicular Tools", ko: "차량 예비 부품 및 액세서리 > 차량 공구" },
  { en: "Spare Parts and Accessories for Vehicles > Vehicular Safety", ko: "차량 예비 부품 및 액세서리 > 차량 안전 용품" },
  { en: "Spare Parts and Accessories for Vehicles > Vehicular Care", ko: "차량 예비 부품 및 액세서리 > 차량 관리 용품" },
  { en: "Spare Parts and Accessories for Vehicles > Others", ko: "차량 예비 부품 및 액세서리 > 기타" }
];
